### PR TITLE
Updated mod_case.c to provide directory case insensitivity

### PR DESCRIPTION
**Pull request by mdell-seradex**
Hi @Castaglia
I commented out your original "static void case_replace_path", as well as certain lines of code in the hopes that you could see more clearly what changes I made, however I can see that they could simply make things harder to read.

I only replaced the one call in `case_pre_cmd` from `case_have_file` (plus surrounding code) to `find_path_case_insensitive`.  The other methods that call `case_have_file` were not changed, but could be updated in a similar fashion.
I did not change those as it took a bit for me to get this working and I did not require the others.

One thing I am concerned about is memory management due to creation of new strings, but I tried to follow the pattern you had laid out in your current version.  I even made a few of the changes that you just checked in yesterday since I had started with a previous version on `mod_case.c`, however I did bring it up to match your current checked in version with my changes included.

I am willing to make any changes prior to finalization including removal of commented out methods.
Please feel free to make changes yourself to improve this code.

Let me know what you think about this.
Mark

### CODE REVIEW

**Comment by mdell-seradex** [comment]
I can do that.
Wait, I did 4 space indentation?  Not intentionally I think.

**Comment by Castaglia** [comment]
What is the specific use case/functionality you are trying to achieve?  Please start with a description of that.  That description will help me understand why you are making the code changes presented.

**Comment by mdell-seradex** [comment]
Should I just remove the commented out code?
Example:
```
//static void case_replace_path(cmd_rec *cmd, const char *proto, const char *dir,
//    const char *file, int path_index) {

//  /* Minor nit: if dir is "//", then reduce it to just "/". */
//  if (strcmp(dir, "//") == 0) {
//    dir = pstrdup(cmd->tmp_pool, "/");
//  }
...
//    return;
//  }
//}
```

Instead of changing it to this:
```
/*
static void case_replace_path(cmd_rec *cmd, const char *proto, const char *dir,
    const char *file, int path_index) {

  /* Minor nit: if dir is "//", then reduce it to just "/". */
  if (strcmp(dir, "//") == 0) {
    dir = pstrdup(cmd->tmp_pool, "/");
  }
...
    return;
  }
}
*/

**Comment by mdell-seradex** [comment]
@Castaglia, should I just remove the commented out code?
Example:
```
//static void case_replace_path(cmd_rec *cmd, const char *proto, const char *dir,
//    const char *file, int path_index) {

//  /* Minor nit: if dir is "//", then reduce it to just "/". */
//  if (strcmp(dir, "//") == 0) {
...
//    return;
//  }
//}
```

Instead of changing it to this:
```
/*
static void case_replace_path(cmd_rec *cmd, const char *proto, const char *dir,
    const char *file, int path_index) {

  /* Minor nit: if dir is "//", then reduce it to just "/". */
  if (strcmp(dir, "//") == 0) {
...
    return;
  }
}
*/
```
Or is this better:
```
/*static void case_replace_path(cmd_rec *cmd, const char *proto, const char *dir,
 *    const char *file, int path_index) {
 *
 *  /* Minor nit: if dir is "//", then reduce it to just "/". */
 *  if (strcmp(dir, "//") == 0) {
...
 *    return;
 *  }
 *}
 */
```

**Comment by mdell-seradex** [comment]
I created mdell-seradex/proftpd-mod_case#1 as requested and it provides an example of the situation this addresses.
Note that the pull request does not currently handle all requests, but only those handled by `case_pre_cmd`.  I thought this was a good start and could be altered to handle the other methods as well, prior to merging.
Hopefully the changes thus far are done well, with the exception of the formatting that you have mentioned.

**Comment by mdell-seradex** [comment]
Hi @Castaglia.
I have reviewed some of the history of the proftpd src and can see that it seems you do not keep old code like I have done here.  I will modify my changes to conform to that.  I have gotten used to certain practises because some developers have inadvertently deleted code that should not have been which is why I did my changes like this.

**Comment by Castaglia** [comment]
I don't keep old code in current files; that is what a source code control system is for (tracking the old code).

I'll take a look at the use case you provided, to better understand this PR.

**Comment by mdell-seradex** [comment]
Hi @Castaglia. 
I cleaned up the code that I checked in. It was inadvertently automatically modified by the IDE I used one time.
It now only shows real changes that I made for this.
That said, if you develop a better way, I'm all for it.

I also hope to track down the cause of mdell-seradex/proftpd-mod_case#2.

**Comment by mdell-seradex** [comment]
Hello @Castaglia.
I just wanted to say that I have no issues with you making changes directly in my repository if you wish.
I also believe I know what needs to be done to make the remaining changes so that this behaviour work for all commands, essentially replacing all uses of `case_have_file` with `find_path_case_insensitive`.  
I just want to confirm that my belief which I have posed as mdell-seradex/proftpd-mod_case#3 is correct, before I attempt that.
Also I don't really have a good way to test all of the affected commands through all the connection types.  For example, it looks like things might be different when the `sftp` proto is used.
I am not even certain what they all are.

**Comment by mdell-seradex** [comment]
Hello again, @Castaglia.
I have merged your recent changes upstream into my repro.
This leaves only this issue remaining.
If there is anything else I can provide you to help with completing this, please let me know.

Thank you
Mark

**Comment by mdell-seradex** [comment]
Thanks to the completion of Castaglia#5, this is no longer required.
He has taken a different approach that works well in my tests.

**Pull request closed without merging**
